baseurl = "/"
relativeurls = true
languageCode = "en-us"
title = "bloggers"
theme = "hugo_theme_robust"
googleAnalytics = "UA-101160377-1"
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
pluralizeListTitles = false

[params]
  maxChars = 750

